name: opus-tools

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: build ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # arch: [x86_64, x86, aarch64, armhf]
          arch: [x86_64]
          os: [ubuntu-latest]
          branch: [latest-stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-opus-tools-${{ matrix.branch }}-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ccache-opus-tools-${{ matrix.branch }}-${{ matrix.arch }}-

      - name: Setup Alpine Linux for ${{ matrix.arch }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.arch }}
          branch: ${{ matrix.branch }}
          packages: >
            bash build-base ccache clang lld coreutils findutils gawk git grep tar xz
            autoconf automake libtool pkgconf gettext
          shell-name: alpine.sh

      - name: Build Opus tools inside chroot
        id: build
        env:
          ARCH: ${{ matrix.arch }}
          BRANCH: ${{ matrix.branch }}
        shell: alpine.sh {0}
        run: |
          bash -x opus-tools/build.sh

      - name: Upload artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: opus-tools-${{ matrix.arch }}
          path: ./**/opus-tools*.tar.*

  release:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Get commit date
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "DATE=$(gh api repos/$REPO/commits/$SHA --jq '.commit.committer.date' | date -f - +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: false
          tag_name: latest
          name: ${{ env.DATE }}
          body: |
            
          files: |
            ./**/opus-tools*.tar.*
